version: "3.7"

services:
  postgres:
    image: postgres:12.1
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: postgres_techcoder
    ports:
      - 5434:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data  # 여기에서 로컬 디렉토리를 사용
    networks:
      - postgres-network

networks:
  postgres-network:  # 네트워크 정의
